<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provinces = [
            ['name' => 'Chachapoyas', 'location_department_id' => 1],
            ['name' => 'Bagua', 'location_department_id' => 1],
            ['name' => 'Bongará', 'location_department_id' => 1],
            ['name' => 'Condorcanqui', 'location_department_id' => 1],
            ['name' => 'Luya', 'location_department_id' => 1],
            ['name' => 'Rodríguez de Mendoza', 'location_department_id' => 1],
            ['name' => 'Utcubamba', 'location_department_id' => 1],
            ['name' => 'Huaraz', 'location_department_id' => 2],
            ['name' => 'Aija', 'location_department_id' => 2],
            ['name' => 'Antonio Raymondi', 'location_department_id' => 2],
            ['name' => 'Asunción', 'location_department_id' => 2],
            ['name' => 'Bolognesi', 'location_department_id' => 2],
            ['name' => 'Carhuaz', 'location_department_id' => 2],
            ['name' => 'Carlos Fermín Fitzcarrald', 'location_department_id' => 2],
            ['name' => 'Casma', 'location_department_id' => 2],
            ['name' => 'Corongo', 'location_department_id' => 2],
            ['name' => 'Huari', 'location_department_id' => 2],
            ['name' => 'Huarmey', 'location_department_id' => 2],
            ['name' => 'Huaylas', 'location_department_id' => 2],
            ['name' => 'Mariscal Luzuriaga', 'location_department_id' => 2],
            ['name' => 'Ocros', 'location_department_id' => 2],
            ['name' => 'Pallasca', 'location_department_id' => 2],
            ['name' => 'Pomabamba', 'location_department_id' => 2],
            ['name' => 'Recuay', 'location_department_id' => 2],
            ['name' => 'Santa', 'location_department_id' => 2],
            ['name' => 'Sihuas', 'location_department_id' => 2],
            ['name' => 'Yungay', 'location_department_id' => 2],
            ['name' => 'Abancay', 'location_department_id' => 3],
            ['name' => 'Andahuaylas', 'location_department_id' => 3],
            ['name' => 'Antabamba', 'location_department_id' => 3],
            ['name' => 'Aymaraes', 'location_department_id' => 3],
            ['name' => 'Cotabambas', 'location_department_id' => 3],
            ['name' => 'Chincheros', 'location_department_id' => 3],
            ['name' => 'Grau', 'location_department_id' => 3],
            ['name' => 'Arequipa', 'location_department_id' => 4],
            ['name' => 'Camaná', 'location_department_id' => 4],
            ['name' => 'Caravelí', 'location_department_id' => 4],
            ['name' => 'Castilla', 'location_department_id' => 4],
            ['name' => 'Caylloma', 'location_department_id' => 4],
            ['name' => 'Condesuyos', 'location_department_id' => 4],
            ['name' => 'Islay', 'location_department_id' => 4],
            ['name' => 'La Uniòn', 'location_department_id' => 4],
            ['name' => 'Huamanga', 'location_department_id' => 5],
            ['name' => 'Cangallo', 'location_department_id' => 5],
            ['name' => 'Huanca Sancos', 'location_department_id' => 5],
            ['name' => 'Huanta', 'location_department_id' => 5],
            ['name' => 'La Mar', 'location_department_id' => 5],
            ['name' => 'Lucanas', 'location_department_id' => 5],
            ['name' => 'Parinacochas', 'location_department_id' => 5],
            ['name' => 'Pàucar del Sara Sara', 'location_department_id' => 5],
            ['name' => 'Sucre', 'location_department_id' => 5],
            ['name' => 'Víctor Fajardo', 'location_department_id' => 5],
            ['name' => 'Vilcas Huamán', 'location_department_id' => 5],
            ['name' => 'Cajamarca', 'location_department_id' => 6],
            ['name' => 'Cajabamba', 'location_department_id' => 6],
            ['name' => 'Celendín', 'location_department_id' => 6],
            ['name' => 'Chota', 'location_department_id' => 6],
            ['name' => 'Contumazá', 'location_department_id' => 6],
            ['name' => 'Cutervo', 'location_department_id' => 6],
            ['name' => 'Hualgayoc', 'location_department_id' => 6],
            ['name' => 'Jaén', 'location_department_id' => 6],
            ['name' => 'San Ignacio', 'location_department_id' => 6],
            ['name' => 'San Marcos', 'location_department_id' => 6],
            ['name' => 'San Miguel', 'location_department_id' => 6],
            ['name' => 'San Pablo', 'location_department_id' => 6],
            ['name' => 'Santa Cruz', 'location_department_id' => 6],
            ['name' => 'Prov. Const. del Callao', 'location_department_id' => 7],
            ['name' => 'Cusco', 'location_department_id' => 8],
            ['name' => 'Acomayo', 'location_department_id' => 8],
            ['name' => 'Anta', 'location_department_id' => 8],
            ['name' => 'Calca', 'location_department_id' => 8],
            ['name' => 'Canas', 'location_department_id' => 8],
            ['name' => 'Canchis', 'location_department_id' => 8],
            ['name' => 'Chumbivilcas', 'location_department_id' => 8],
            ['name' => 'Espinar', 'location_department_id' => 8],
            ['name' => 'La Convención', 'location_department_id' => 8],
            ['name' => 'Paruro', 'location_department_id' => 8],
            ['name' => 'Paucartambo', 'location_department_id' => 8],
            ['name' => 'Quispicanchi', 'location_department_id' => 8],
            ['name' => 'Urubamba', 'location_department_id' => 8],
            ['name' => 'Huancavelica', 'location_department_id' => 9],
            ['name' => 'Acobamba', 'location_department_id' => 9],
            ['name' => 'Angaraes', 'location_department_id' => 9],
            ['name' => 'Castrovirreyna', 'location_department_id' => 9],
            ['name' => 'Churcampa', 'location_department_id' => 9],
            ['name' => 'Huaytará', 'location_department_id' => 9],
            ['name' => 'Tayacaja', 'location_department_id' => 9],
            ['name' => 'Huánuco', 'location_department_id' => 10],
            ['name' => 'Ambo', 'location_department_id' => 10],
            ['name' => 'Dos de Mayo', 'location_department_id' => 10],
            ['name' => 'Huacaybamba', 'location_department_id' => 10],
            ['name' => 'Huamalíes', 'location_department_id' => 10],
            ['name' => 'Leoncio Prado', 'location_department_id' => 10],
            ['name' => 'Marañón', 'location_department_id' => 10],
            ['name' => 'Pachitea', 'location_department_id' => 10],
            ['name' => 'Puerto Inca', 'location_department_id' => 10],
            ['name' => 'Lauricocha ', 'location_department_id' => 10],
            ['name' => 'Yarowilca ', 'location_department_id' => 10],
            ['name' => 'Ica ', 'location_department_id' => 11],
            ['name' => 'Chincha ', 'location_department_id' => 11],
            ['name' => 'Nasca ', 'location_department_id' => 11],
            ['name' => 'Palpa ', 'location_department_id' => 11],
            ['name' => 'Pisco ', 'location_department_id' => 11],
            ['name' => 'Huancayo ', 'location_department_id' => 12],
            ['name' => 'Concepción ', 'location_department_id' => 12],
            ['name' => 'Chanchamayo ', 'location_department_id' => 12],
            ['name' => 'Jauja ', 'location_department_id' => 12],
            ['name' => 'Junín ', 'location_department_id' => 12],
            ['name' => 'Satipo ', 'location_department_id' => 12],
            ['name' => 'Tarma ', 'location_department_id' => 12],
            ['name' => 'Yauli ', 'location_department_id' => 12],
            ['name' => 'Chupaca ', 'location_department_id' => 12],
            ['name' => 'Trujillo ', 'location_department_id' => 13],
            ['name' => 'Ascope ', 'location_department_id' => 13],
            ['name' => 'Bolívar ', 'location_department_id' => 13],
            ['name' => 'Chepén ', 'location_department_id' => 13],
            ['name' => 'Julcán ', 'location_department_id' => 13],
            ['name' => 'Otuzco ', 'location_department_id' => 13],
            ['name' => 'Pacasmayo ', 'location_department_id' => 13],
            ['name' => 'Pataz ', 'location_department_id' => 13],
            ['name' => 'Sánchez Carrión ', 'location_department_id' => 13],
            ['name' => 'Santiago de Chuco ', 'location_department_id' => 13],
            ['name' => 'Gran Chimú ', 'location_department_id' => 13],
            ['name' => 'Virú ', 'location_department_id' => 13],
            ['name' => 'Chiclayo ', 'location_department_id' => 14],
            ['name' => 'Ferreñafe ', 'location_department_id' => 14],
            ['name' => 'Lambayeque ', 'location_department_id' => 14],
            ['name' => 'Lima ', 'location_department_id' => 15],
            ['name' => 'Barranca ', 'location_department_id' => 15],
            ['name' => 'Cajatambo ', 'location_department_id' => 15],
            ['name' => 'Canta ', 'location_department_id' => 15],
            ['name' => 'Cañete ', 'location_department_id' => 15],
            ['name' => 'Huaral ', 'location_department_id' => 15],
            ['name' => 'Huarochirí ', 'location_department_id' => 15],
            ['name' => 'Huaura ', 'location_department_id' => 15],
            ['name' => 'Oyón ', 'location_department_id' => 15],
            ['name' => 'Yauyos ', 'location_department_id' => 15],
            ['name' => 'Maynas ', 'location_department_id' => 16],
            ['name' => 'Alto Amazonas ', 'location_department_id' => 16],
            ['name' => 'Loreto ', 'location_department_id' => 16],
            ['name' => 'Mariscal Ramón Castilla ', 'location_department_id' => 16],
            ['name' => 'Requena ', 'location_department_id' => 16],
            ['name' => 'Ucayali ', 'location_department_id' => 16],
            ['name' => 'Datem del Marañón ', 'location_department_id' => 16],
            ['name' => 'Putumayo', 'location_department_id' => 16],
            ['name' => 'Tambopata ', 'location_department_id' => 17],
            ['name' => 'Manu ', 'location_department_id' => 17],
            ['name' => 'Tahuamanu ', 'location_department_id' => 17],
            ['name' => 'Mariscal Nieto ', 'location_department_id' => 18],
            ['name' => 'General Sánchez Cerro ', 'location_department_id' => 18],
            ['name' => 'Ilo ', 'location_department_id' => 18],
            ['name' => 'Pasco ', 'location_department_id' => 19],
            ['name' => 'Daniel Alcides Carrión ', 'location_department_id' => 19],
            ['name' => 'Oxapampa ', 'location_department_id' => 19],
            ['name' => 'Piura ', 'location_department_id' => 20],
            ['name' => 'Ayabaca ', 'location_department_id' => 20],
            ['name' => 'Huancabamba ', 'location_department_id' => 20],
            ['name' => 'Morropón ', 'location_department_id' => 20],
            ['name' => 'Paita ', 'location_department_id' => 20],
            ['name' => 'Sullana ', 'location_department_id' => 20],
            ['name' => 'Talara ', 'location_department_id' => 20],
            ['name' => 'Sechura ', 'location_department_id' => 20],
            ['name' => 'Puno ', 'location_department_id' => 21],
            ['name' => 'Azángaro ', 'location_department_id' => 21],
            ['name' => 'Carabaya ', 'location_department_id' => 21],
            ['name' => 'Chucuito ', 'location_department_id' => 21],
            ['name' => 'El Collao ', 'location_department_id' => 21],
            ['name' => 'Huancané ', 'location_department_id' => 21],
            ['name' => 'Lampa ', 'location_department_id' => 21],
            ['name' => 'Melgar ', 'location_department_id' => 21],
            ['name' => 'Moho ', 'location_department_id' => 21],
            ['name' => 'San Antonio de Putina ', 'location_department_id' => 21],
            ['name' => 'San Román ', 'location_department_id' => 21],
            ['name' => 'Sandia ', 'location_department_id' => 21],
            ['name' => 'Yunguyo ', 'location_department_id' => 21],
            ['name' => 'Moyobamba ', 'location_department_id' => 22],
            ['name' => 'Bellavista ', 'location_department_id' => 22],
            ['name' => 'El Dorado ', 'location_department_id' => 22],
            ['name' => 'Huallaga ', 'location_department_id' => 22],
            ['name' => 'Lamas ', 'location_department_id' => 22],
            ['name' => 'Mariscal Cáceres ', 'location_department_id' => 22],
            ['name' => 'Picota ', 'location_department_id' => 22],
            ['name' => 'Rioja ', 'location_department_id' => 22],
            ['name' => 'San Martín ', 'location_department_id' => 22],
            ['name' => 'Tocache ', 'location_department_id' => 22],
            ['name' => 'Tacna ', 'location_department_id' => 23],
            ['name' => 'Candarave ', 'location_department_id' => 23],
            ['name' => 'Jorge Basadre ', 'location_department_id' => 23],
            ['name' => 'Tarata ', 'location_department_id' => 23],
            ['name' => 'Tumbes ', 'location_department_id' => 24],
            ['name' => 'Contralmirante Villar ', 'location_department_id' => 24],
            ['name' => 'Zarumilla ', 'location_department_id' => 24],
            ['name' => 'Coronel Portillo ', 'location_department_id' => 25],
            ['name' => 'Atalaya ', 'location_department_id' => 25],
            ['name' => 'Padre Abad ', 'location_department_id' => 25],
            ['name' => 'Purús', 'location_department_id' => 25],
        ];

        DB::table('location_provinces')->insert($provinces);
    }
}
